inherit_from: '.rubocop_todo.yml'

AllCops:
  Include:
    - 'message-driver.gemspec'
    - '**/Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Style/AccessorMethodName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/BlockNesting:
  Max: 4

Style/FileName:
  Exclude:
    - 'lib/message-driver.rb'

Style/NumericLiterals:
  Enabled: false
