inherit_from: '.rubocop_todo.yml'

AllCops:
  Include:
    - 'message-driver.gemspec'
    - '**/Gemfile'
    - 'Guardfile'
    - 'Rakefile'
  Exclude:
    - 'lib/vendor/**/*.rb'
    - 'vendor/**/*'

Metrics/BlockNesting:
  Max: 4

Metrics/LineLength:
  AllowURI: true
  Max: 120
  Include:
    - 'lib/**/*.rb'

Style/AccessorMethodName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/message-driver.rb'

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true
  AllowDSLWriters: true
