language: ruby
sudo: required
before_install: gem install bundler
bundler_args: --without tools darwin
services:
  - rabbitmq
before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
script: bundle exec rake ci
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
env:
  - ADAPTER=in_memory
  - ADAPTER=bunny:2.7.4
  - ADAPTER=bunny:2.8.1
  - ADAPTER=bunny:2.9.2
  - ADAPTER=stomp:1.3.1
matrix:
  fast_finish: true
