language: ruby
cache: bundler
bundler_args: --without tools darwin
services:
  - rabbitmq
before_script:
  - ci/travis_setup
script: bundle exec rake ci
rvm:
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - 1.9.2
  - rbx-2
env:
  - ADAPTER=in_memory
  - ADAPTER=bunny:1.2.2
  - ADAPTER=bunny:1.3.1
  - ADAPTER=bunny:1.4.1
  - ADAPTER=bunny:1.5.0
  - ADAPTER=stomp
matrix:
  allow_failures:
    - rvm: jruby-19mode
      env: ADAPTER=stomp
    - env: ADAPTER=bunny:1.5.0
