language: ruby
bundler_args: --without tools darwin
services:
  - rabbitmq
before_script:
  - ci/travis_setup
script: bundle exec rake ci
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - 1.9.2
  - rbx-2
env:
  - ADAPTER=in_memory
  - ADAPTER=bunny:1.7.0
  - ADAPTER=bunny:2.0.1
  - ADAPTER=bunny:2.1.0
  - ADAPTER=stomp
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
      env: ADAPTER=stomp
    - rvm: 2.2
  exclude:
    - rvm: 1.9.2
      env: ADAPTER=bunny:2.0.1
    - rvm: 1.9.3
      env: ADAPTER=bunny:2.0.1
    - rvm: jruby-19mode
      env: ADAPTER=bunny:2.0.1
    - rvm: 1.9.2
      env: ADAPTER=bunny:2.1.0
    - rvm: 1.9.3
      env: ADAPTER=bunny:2.1.0
    - rvm: jruby-19mode
      env: ADAPTER=bunny:2.1.0
