language: ruby
bundler_args: --without tools darwin
services:
  - rabbitmq
before_script:
  - sudo rabbitmqctl add_vhost message-driver-test
  - sudo rabbitmqctl set_permissions -p message-driver-test guest ".*" ".*" ".*"
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
env:
  - ADAPTER=in_memory
  - ADAPTER=stomp
  - ADAPTER=bunny:1.1.3
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - 1.9.2
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-19mode
      env: ADAPTER=stomp
