language: ruby
bundler_args: --without tools darwin
services:
  - rabbitmq
before_script:
  - sudo rabbitmqctl add_vhost message-driver-test
  - sudo rabbitmqctl set_permissions -p message-driver-test guest ".*" ".*" ".*"
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
env:
  - ADAPTER=in_memory
  - ADAPTER=bunny:0.10.0
  - ADAPTER=stomp
  - ADAPTER=bunny:1.0.0
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - jruby-head
  - rbx-19mode
matrix:
  exclude:
    - rvm: jruby-19mode
      env: ADAPTER=bunny:0.9.0
    - rvm: jruby-head
      env: ADAPTER=bunny:0.9.0
  allow_failures:
    - env: ADAPTER=bunny:1.0.0.rc
    - rvm: jruby-head
    - rvm: rbx-19mode
    - rvm: jruby-19mode
      env: ADAPTER=stomp
