language: ruby
bundler_args: --without tools darwin
services:
  - rabbitmq
before_script:
  - sudo rabbitmqctl add_vhost message-driver-test
  - sudo rabbitmqctl set_permissions -p message-driver-test guest ".*" ".*" ".*"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head
  - jruby-head
  - rbx-19mode
env:
  - ADAPTER=in_memory
  - ADAPTER=bunny
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-19mode
