language: ruby
cache: bundler
bundler_args: --without tools darwin
services:
  - rabbitmq
before_script:
  - ci/travis_setup
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - 1.9.2
  - rbx
env:
  - ADAPTER=in_memory
  - ADAPTER=stomp
  - ADAPTER=bunny:1.1.3
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-19mode
      env: ADAPTER=stomp
