#!/bin/bash

#vhost="message-driver-test-$ADAPTER-$(rbenv version-name)"
vhost="message-driver-test"

echo $vhost

rabbitmqctl delete_vhost $vhost
rabbitmqctl add_vhost $vhost
rabbitmqctl set_permissions -p $vhost guest ".*" ".*" ".*"
